enyo.depends(
    "source/EnyoPlatform.js",
    "source/globals.js",
    "utilkinds.js",
    "source/contactDetail.js",
    "source/outboxHandler.js",
    "source/popups.js",
    "source/contactsIndex.js",
    "source/gvoice.js",
    "css/gvoice.css"
);
